name: Deploy gitbook with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '10.14.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install gitbook cli
        run: npm install -g gitbook-cli
      - name: Install gitbook Plugin
        run:  gitbook install
      - name: build website
        run: |
          gitbook build . ./build
          rm -rf ./build/.github
          echo "" > ./build/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
